export const SOCIETIES_LOADING = "SOCIETIES_LOADING";
export const SOCIETIES_SUCCESS = "SOCIETIES_SUCCESS";
export const SOCIETIES_FAILED = "SOCIETIES_FAILED"
export const SOCIETY_LOADING = "SOCIETY_LOADING";
export const SOCIETY_SUCCESS = "SOCIETY_SUCCESS";
export const SOCIETY_FAILED = "SOCIETY_FAILED"