export const SIGNUP_USERS_LOADING = 'SIGNUP_USERS_LOADING'
export const SIGNUP_USERS_FAILURE = 'SIGNUP_USERS_FAILURE'
export const SIGNUP_USERS_SUCCESS = 'SIGNUP_USERS_SUCCESS'

export const LOGIN_USERS_LOADING = 'LOGIN_USERS_LOADING'
export const LOGIN_USERS_FAILURE = 'LOGIN_USERS_FAILURE'
export const LOGIN_USERS_SUCCESS = 'LOGIN_USERS_SUCCESS'

export const REFRESH_USER = 'REFRESH_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

export const EDIT_USER_LOADING = 'EDIT_USER_LOADING'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE'


export const PARTICIPANT_USER_LOADING = 'PARTICIPANT_USER_LOADING'
export const PARTICIPANT_USER_SUCCESS = 'PARTICIPANT_USER_SUCCESS'
export const PARTICIPANT_USER_FAILURE = 'PARTICIPANT_USER_FAILURE'


export const QUESTION_USER_LOADING = 'QUESTION_USER_LOADING'
export const QUESTION_USER_SUCCESS = 'QUESTION_USER_SUCCESS'
export const QUESTION_USER_FAILURE = 'QUESTION_USER_FAILURE'